name: Portfolio Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install AzCopy
        run: |
          wget -O azcopy.tar.gz https://aka.ms/downloadazcopy-v10-linux
          tar -xf azcopy.tar.gz
          sudo cp ./azcopy_linux_amd64_*/azcopy /usr/local/bin/

      - name: Upload Website
        run: |
        cd tws-portfolio
        azcopy copy "." "https://githubproject.blob.core.windows.net/\$web?${{ secrets.AZURE_WEB_CONTAINER_SAS }}" --recursive=true
