name: Portfolio Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install AzCopy
        run: |
          wget https://aka.ms/downloadazcopy-v10-linux -O azcopy.tar.gz
          tar -xvf azcopy.tar.gz
          sudo cp ./azcopy_linux_amd64_*/azcopy /usr/local/bin/

      - name: Upload Website Files
        run: |
          azcopy sync "." "${{ secrets.AZURE_WEB_CONTAINER_URL }}?${{ secrets.AZURE_WEB_CONTAINER_SAS }}" --recursive=true
