name: Portfolio Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Upload Website to Azure Storage
        uses: azure/CLI@v2
        with:
          inlineScript: |
            az storage blob upload-batch \
              --connection-string "${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}" \
              --destination '$web' \
              --source . \
              --overwrite
